# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
   build:

    docker:
      # specify the version you desire here
      - image: cimg/android:2023.06
      # - image: circleci/android:api-28
      # - image: circleci/openjdk:latest


    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx4096m
    # Add steps to the job

    steps:
      - checkout
      - run:
          name: Fetch Commit Count
          command: |
            git remote set-url origin https://github.com/tr-sangale/firstAndroidLibrary
            git fetch
            BRANCH_NAME="${CIRCLE_BRANCH}"
            COMMIT_COUNT=$(git rev-list --count origin/$BRANCH_NAME)
            echo "Commit Count for branch $BRANCH_NAME: ${COMMIT_COUNT}"
      - run:
          name: settting up package version which needs to download
          command: |
            PACKAGE_VERSION="NEW-${COMMIT_COUNT}-"${BRANCH_NAME}"
      - run: 
          name: change the permission
          command: chmod +x ./gradlew

      # # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: 
          name: download gradle dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
   

      # build the androidlib
     
      - run: 
          name: build project
          command: ./gradlew build

      # run tests!
      - run: 
          name: gradle unit tests
          command: ./gradlew test
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build:
    jobs:
      - build
